{
	
gROOT->ForceStyle(); 
gStyle->SetPadLeftMargin(0.18);
gStyle->SetPadRightMargin(0.18);
gStyle->SetPadBottomMargin(0.13);
gStyle->SetOptStat(0);


TCanvas *trueH= new TCanvas ("trueH", "trueH", 700, 700);
trueH->Divide(2,2);

TFile *file=0;
file=TFile::Open("Histos_ch0_err3_sm0_MCf0_PID1_smear0_scale0.root");

trueH->cd(1);
gPad->SetLogx();
//gPad->SetLogy();
gPad->SetTicks();
TH1F * trueHistMCDivide = new TH1F("trueHistMCDivide","trueHistMCDivide",1,10,1000);
trueHistMCDivide->SetMaximum(1.3);
trueHistMCDivide->SetMinimum(0);
trueHistMCDivide->SetTitle("Electron channel");
trueHistMCDivide->SetLineWidth(2);
trueHistMCDivide->SetLineStyle(kSolid);
trueHistMCDivide->SetLineColor(kBlack);
trueHistMCDivide->GetXaxis()->SetTitle("True photon p_{T} [GeV]"); 
trueHistMCDivide->GetYaxis()->SetTitle("Unfolding correction factor"); 
trueHistMCDivide->GetXaxis()->SetMoreLogLabels(); 
trueHistMCDivide->GetYaxis()->SetMoreLogLabels(); 
trueHistMCDivide->GetXaxis()->SetTitleOffset(1.3); 
trueHistMCDivide->GetYaxis()->SetTitleOffset(1.7); 
trueHistMCDivide->GetXaxis()->SetLabelFont(62); 
trueHistMCDivide->GetYaxis()->SetLabelFont(62); 
trueHistMCDivide->GetXaxis()->SetTitleFont(62); 
trueHistMCDivide->GetYaxis()->SetTitleFont(62); 
trueHistMCDivide->GetXaxis()->SetLabelSize(0.045); 
trueHistMCDivide->GetYaxis()->SetLabelSize(0.045); 
trueHistMCDivide->GetXaxis()->SetTitleSize(0.048); 
trueHistMCDivide->GetYaxis()->SetTitleSize(0.048); 
trueHistMCDivide->GetXaxis()->SetNoExponent(); 
trueHistMCDivide->GetYaxis()->SetNoExponent(); 
trueHistMCDivide->Draw();
outHistBayes4MCDivide->SetLineWidth(2);
outHistBayes4MCDivide->SetLineStyle(kDashed);
outHistBayes4MCDivide->SetLineColor(kRed);
outHistBayes4MCDivide->Draw("same");

file=TFile::Open("Histos_ch0_err3_sm0_MCf0_PID1_smear0_scale1.root");
outHistBayes4MCDivide->SetLineWidth(2);
outHistBayes4MCDivide->SetLineStyle(kDotted);
outHistBayes4MCDivide->SetLineColor(kCyan);
outHistBayes4MCDivide->Draw("same");
file=TFile::Open("Histos_ch0_err3_sm0_MCf0_PID1_smear0_scale-1.root");
outHistBayes4MCDivide->SetLineWidth(2);
outHistBayes4MCDivide->SetLineStyle(kDotted);
outHistBayes4MCDivide->SetLineColor(kBlue);
outHistBayes4MCDivide->Draw("same");
file=TFile::Open("Histos_ch0_err3_sm0_MCf0_PID1_smear1_scale0.root");
outHistBayes4MCDivide->SetLineWidth(2);
outHistBayes4MCDivide->SetLineStyle(kDashDotted);
outHistBayes4MCDivide->SetLineColor(kYellow);
outHistBayes4MCDivide->Draw("same");
file=TFile::Open("Histos_ch0_err3_sm0_MCf0_PID1_smear1_scale1.root");
outHistBayes4MCDivide->SetLineWidth(2);
outHistBayes4MCDivide->SetLineStyle(kDashDotted);
outHistBayes4MCDivide->SetLineColor(kGreen);
outHistBayes4MCDivide->Draw("same");
file=TFile::Open("Histos_ch0_err3_sm0_MCf0_PID1_smear1_scale-1.root");
outHistBayes4MCDivide->SetLineWidth(2);
outHistBayes4MCDivide->SetLineStyle(kDotted);
outHistBayes4MCDivide->SetLineColor(kMagenta);
outHistBayes4MCDivide->Draw("same");

TLatex latex;
latex.SetTextFont(62);
latex.SetTextSize(0.045);    
latex.DrawLatex(23,1900,"CMS simulation internal");

TLegend *leg = new TLegend(0.2,0.15,0.8,0.5,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(0);
leg->SetLineStyle(1);
leg->SetLineWidth(1);
leg->SetFillColor(19);
leg->SetFillStyle(0);
TLegendEntry *entry=leg->AddEntry("outHistBayes4MC","outHistBayes4MC","L");
entry->SetLineWidth(2);
entry->SetLineStyle(kDashed);
entry->SetLineColor(kRed);
entry=leg->AddEntry("a","outHistBayes4MC, smear 1%","L");
entry->SetLineWidth(2);
entry->SetLineStyle(kDotted);
entry->SetLineColor(kYellow);
entry=leg->AddEntry("b","outHistBayes4MC, scale +1%","L");
entry->SetLineWidth(2);
entry->SetLineStyle(kDotted);
entry->SetLineColor(kCyan);
entry=leg->AddEntry("c","outHistBayes4MC, scale -1%","L");
entry->SetLineWidth(2);
entry->SetLineStyle(kDotted);
entry->SetLineColor(kBlue);
entry=leg->AddEntry("d","outHistBayes4MC, scale +1%, smear 1%","L");
entry->SetLineWidth(2);
entry->SetLineStyle(kDashDotted);
entry->SetLineColor(kGreen);
entry=leg->AddEntry("e","outHistBayes4MC, scale -1%, smear 1%","L");
entry->SetLineWidth(2);
entry->SetLineStyle(kDashDotted);
entry->SetLineColor(kMagenta);
leg->Draw();

trueH->cd(3);
gPad->SetLogx();
//gPad->SetLogy();
gPad->SetTicks();
file=TFile::Open("Histos_ch0_err3_sm0_MCf0_PID1_smear0_scale0.root");
TH1F * trueHistMassMCDivide = new TH1F("trueHistMassMCDivide","trueHistMassMCDivide",1,50,1000);
trueHistMassMCDivide->SetMaximum(4.);
trueHistMassMCDivide->SetMinimum(0.5);
trueHistMassMCDivide->SetTitle("Electron channel");
trueHistMassMCDivide->SetLineWidth(2);
trueHistMassMCDivide->SetLineStyle(kSolid);
trueHistMassMCDivide->SetLineColor(kBlack);
trueHistMassMCDivide->GetXaxis()->SetTitle("True ll#gamma mass [GeV]"); 
trueHistMassMCDivide->GetYaxis()->SetTitle("Unfolding correction factor"); 
trueHistMassMCDivide->GetXaxis()->SetMoreLogLabels(); 
trueHistMassMCDivide->GetYaxis()->SetMoreLogLabels(); 
trueHistMassMCDivide->GetXaxis()->SetTitleOffset(1.3); 
trueHistMassMCDivide->GetYaxis()->SetTitleOffset(1.7); 
trueHistMassMCDivide->GetXaxis()->SetLabelFont(62); 
trueHistMassMCDivide->GetYaxis()->SetLabelFont(62); 
trueHistMassMCDivide->GetXaxis()->SetTitleFont(62); 
trueHistMassMCDivide->GetYaxis()->SetTitleFont(62); 
trueHistMassMCDivide->GetXaxis()->SetLabelSize(0.045); 
trueHistMassMCDivide->GetYaxis()->SetLabelSize(0.045); 
trueHistMassMCDivide->GetXaxis()->SetTitleSize(0.048); 
trueHistMassMCDivide->GetYaxis()->SetTitleSize(0.048); 
trueHistMassMCDivide->GetXaxis()->SetNoExponent(); 
trueHistMassMCDivide->GetYaxis()->SetNoExponent(); 
trueHistMassMCDivide->Draw();
outHistMassBayes4MCDivide->SetLineWidth(2);
outHistMassBayes4MCDivide->SetLineStyle(kDashed);
outHistMassBayes4MCDivide->SetLineColor(kRed);
outHistMassBayes4MCDivide->Draw("same");

file=TFile::Open("Histos_ch0_err3_sm0_MCf0_PID1_smear0_scale1.root");
outHistMassBayes4MCDivide->SetLineWidth(2);
outHistMassBayes4MCDivide->SetLineStyle(kDotted);
outHistMassBayes4MCDivide->SetLineColor(kCyan);
outHistMassBayes4MCDivide->Draw("same");
file=TFile::Open("Histos_ch0_err3_sm0_MCf0_PID1_smear0_scale-1.root");
outHistMassBayes4MCDivide->SetLineWidth(2);
outHistMassBayes4MCDivide->SetLineStyle(kDotted);
outHistMassBayes4MCDivide->SetLineColor(kBlue);
outHistMassBayes4MCDivide->Draw("same");
file=TFile::Open("Histos_ch0_err3_sm0_MCf0_PID1_smear1_scale0.root");
outHistMassBayes4MCDivide->SetLineWidth(2);
outHistMassBayes4MCDivide->SetLineStyle(kDashDotted);
outHistMassBayes4MCDivide->SetLineColor(kYellow);
outHistMassBayes4MCDivide->Draw("same");
file=TFile::Open("Histos_ch0_err3_sm0_MCf0_PID1_smear1_scale1.root");
outHistMassBayes4MCDivide->SetLineWidth(2);
outHistMassBayes4MCDivide->SetLineStyle(kDashDotted);
outHistMassBayes4MCDivide->SetLineColor(kGreen);
outHistMassBayes4MCDivide->Draw("same");
file=TFile::Open("Histos_ch0_err3_sm0_MCf0_PID1_smear1_scale-1.root");
outHistMassBayes4MCDivide->SetLineWidth(2);
outHistMassBayes4MCDivide->SetLineStyle(kDotted);
outHistMassBayes4MCDivide->SetLineColor(kMagenta);
outHistMassBayes4MCDivide->Draw("same");

TLatex latex;
latex.SetTextFont(62);
latex.SetTextSize(0.045);    
latex.DrawLatex(87,1900,"CMS simulation internal");

TLegend *leg = new TLegend(0.25,0.5,0.8,0.85,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(0);
leg->SetLineStyle(1);
leg->SetLineWidth(1);
leg->SetFillColor(19);
leg->SetFillStyle(0);
TLegendEntry *entry=leg->AddEntry("outHistMassBayes4MC","outHistMassBayes4MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDashed);
entry->SetLineColor(kRed);
entry=leg->AddEntry("a","outHistMassBayes4MC, smear 1%","L");
entry->SetLineWidth(2);
entry->SetLineStyle(kDotted);
entry->SetLineColor(kYellow);
entry=leg->AddEntry("b","outHistMassBayes4MC, scale +1%","L");
entry->SetLineWidth(2);
entry->SetLineStyle(kDotted);
entry->SetLineColor(kCyan);
entry=leg->AddEntry("c","outHistMassBayes4MC, scale -1%","L");
entry->SetLineWidth(2);
entry->SetLineStyle(kDotted);
entry->SetLineColor(kBlue);
entry=leg->AddEntry("d","outHistMassBayes4MC, scale +1%, smear 1%","L");
entry->SetLineWidth(2);
entry->SetLineStyle(kDashDotted);
entry->SetLineColor(kGreen);
entry=leg->AddEntry("e","outHistMassBayes4MC, scale -1%, smear 1%","L");
entry->SetLineWidth(2);
entry->SetLineStyle(kDashDotted);
entry->SetLineColor(kMagenta);
leg->Draw();


file=TFile::Open("Histos_ch1_err3_sm0_MCf0_PID1_smear0_scale0.root");

trueH->cd(2);
gPad->SetLogx();
//gPad->SetLogy();
gPad->SetTicks();
TH1F * trueHistMCDivide1 = new TH1F("trueHistMassMCDivide1","trueHistMassMCDivide1",1,10,1000);
trueHistMCDivide1->SetMaximum(1.3.);
trueHistMCDivide1->SetMinimum(0.);
trueHistMCDivide1->SetTitle("Muon channel");
trueHistMCDivide1->SetLineWidth(2);
trueHistMCDivide1->SetLineStyle(kSolid);
trueHistMCDivide1->SetLineColor(kBlack);
trueHistMCDivide1->GetXaxis()->SetTitle("True photon p_{T} [GeV]"); 
trueHistMCDivide1->GetYaxis()->SetTitle("Unfolding correction factor"); 
trueHistMCDivide1->GetXaxis()->SetMoreLogLabels(); 
trueHistMCDivide1->GetYaxis()->SetMoreLogLabels(); 
trueHistMCDivide1->GetXaxis()->SetTitleOffset(1.3); 
trueHistMCDivide1->GetYaxis()->SetTitleOffset(1.7); 
trueHistMCDivide1->GetXaxis()->SetLabelFont(62); 
trueHistMCDivide1->GetYaxis()->SetLabelFont(62); 
trueHistMCDivide1->GetXaxis()->SetTitleFont(62); 
trueHistMCDivide1->GetYaxis()->SetTitleFont(62); 
trueHistMCDivide1->GetXaxis()->SetLabelSize(0.045); 
trueHistMCDivide1->GetYaxis()->SetLabelSize(0.045); 
trueHistMCDivide1->GetXaxis()->SetTitleSize(0.048); 
trueHistMCDivide1->GetYaxis()->SetTitleSize(0.048); 
trueHistMCDivide1->GetXaxis()->SetNoExponent(); 
trueHistMCDivide1->GetYaxis()->SetNoExponent(); 
trueHistMCDivide1->Draw();
outHistBayes4MCDivide->SetLineWidth(2);
outHistBayes4MCDivide->SetLineStyle(kDashed);
outHistBayes4MCDivide->SetLineColor(kRed);
outHistBayes4MCDivide->Draw("same");

file=TFile::Open("Histos_ch1_err3_sm0_MCf0_PID1_smear0_scale1.root");
outHistBayes4MCDivide->SetLineWidth(2);
outHistBayes4MCDivide->SetLineStyle(kDotted);
outHistBayes4MCDivide->SetLineColor(kCyan);
outHistBayes4MCDivide->Draw("same");
file=TFile::Open("Histos_ch1_err3_sm0_MCf0_PID1_smear0_scale-1.root");
outHistBayes4MCDivide->SetLineWidth(2);
outHistBayes4MCDivide->SetLineStyle(kDotted);
outHistBayes4MCDivide->SetLineColor(kBlue);
outHistBayes4MCDivide->Draw("same");
file=TFile::Open("Histos_ch1_err3_sm0_MCf0_PID1_smear1_scale0.root");
outHistBayes4MCDivide->SetLineWidth(2);
outHistBayes4MCDivide->SetLineStyle(kDashDotted);
outHistBayes4MCDivide->SetLineColor(kYellow);
outHistBayes4MCDivide->Draw("same");
file=TFile::Open("Histos_ch1_err3_sm0_MCf0_PID1_smear1_scale1.root");
outHistBayes4MCDivide->SetLineWidth(2);
outHistBayes4MCDivide->SetLineStyle(kDashDotted);
outHistBayes4MCDivide->SetLineColor(kGreen);
outHistBayes4MCDivide->Draw("same");
file=TFile::Open("Histos_ch1_err3_sm0_MCf0_PID1_smear1_scale-1.root");
outHistBayes4MCDivide->SetLineWidth(2);
outHistBayes4MCDivide->SetLineStyle(kDotted);
outHistBayes4MCDivide->SetLineColor(kMagenta);
outHistBayes4MCDivide->Draw("same");

TLatex latex;
latex.SetTextFont(62);
latex.SetTextSize(0.045);    
latex.DrawLatex(23,2800,"CMS simulation internal");

TLegend *leg = new TLegend(0.2,0.15,0.8,0.5,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(0);
leg->SetLineStyle(1);
leg->SetLineWidth(1);
leg->SetFillColor(19);
leg->SetFillStyle(0);
TLegendEntry *entry=leg->AddEntry("outHistBayes4MC","outHistBayes4MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDashed);
entry->SetLineColor(kRed);
entry=leg->AddEntry("a","outHistBayes4MC, smear 1%","L");
entry->SetLineWidth(2);
entry->SetLineStyle(kDotted);
entry->SetLineColor(kYellow);
entry=leg->AddEntry("b","outHistBayes4MC, scale +1%","L");
entry->SetLineWidth(2);
entry->SetLineStyle(kDotted);
entry->SetLineColor(kCyan);
entry=leg->AddEntry("c","outHistBayes4MC, scale -1%","L");
entry->SetLineWidth(2);
entry->SetLineStyle(kDotted);
entry->SetLineColor(kBlue);
entry=leg->AddEntry("d","outHistBayes4MC, scale +1%, smear 1%","L");
entry->SetLineWidth(2);
entry->SetLineStyle(kDashDotted);
entry->SetLineColor(kGreen);
entry=leg->AddEntry("e","outHistBayes4MC, scale -1%, smear 1%","L");
entry->SetLineWidth(2);
entry->SetLineStyle(kDashDotted);
entry->SetLineColor(kMagenta);
leg->Draw();

trueH->cd(4);
gPad->SetLogx();
//gPad->SetLogy();
gPad->SetTicks();
file=TFile::Open("Histos_ch1_err3_sm0_MCf0_PID1_smear0_scale0.root");
TH1F * trueHistMassMCDivide1 = new TH1F("trueHistMassMCDivide1","trueHistMassMCDivide1",1,50,1000);
trueHistMassMCDivide1->SetMaximum(1.3.);
trueHistMassMCDivide1->SetMinimum(0.);
trueHistMassMCDivide1->SetTitle("Muon channel");
trueHistMassMCDivide1->SetLineWidth(2);
trueHistMassMCDivide1->SetLineStyle(kSolid);
trueHistMassMCDivide1->SetLineColor(kBlack);
trueHistMassMCDivide1->GetXaxis()->SetTitle("True ll#gamma mass [GeV]"); 
trueHistMassMCDivide1->GetYaxis()->SetTitle("Unfolding correction factor"); 
trueHistMassMCDivide1->GetXaxis()->SetMoreLogLabels(); 
trueHistMassMCDivide1->GetYaxis()->SetMoreLogLabels(); 
trueHistMassMCDivide1->GetXaxis()->SetTitleOffset(1.3); 
trueHistMassMCDivide1->GetYaxis()->SetTitleOffset(1.7); 
trueHistMassMCDivide1->GetXaxis()->SetLabelFont(62); 
trueHistMassMCDivide1->GetYaxis()->SetLabelFont(62); 
trueHistMassMCDivide1->GetXaxis()->SetTitleFont(62); 
trueHistMassMCDivide1->GetYaxis()->SetTitleFont(62); 
trueHistMassMCDivide1->GetXaxis()->SetLabelSize(0.045); 
trueHistMassMCDivide1->GetYaxis()->SetLabelSize(0.045); 
trueHistMassMCDivide1->GetXaxis()->SetTitleSize(0.048); 
trueHistMassMCDivide1->GetYaxis()->SetTitleSize(0.048); 
trueHistMassMCDivide1->GetXaxis()->SetNoExponent(); 
trueHistMassMCDivide1->GetYaxis()->SetNoExponent(); 
trueHistMassMCDivide1->Draw();
outHistMassBayes4MCDivide->SetLineWidth(2);
outHistMassBayes4MCDivide->SetLineStyle(kDashed);
outHistMassBayes4MCDivide->SetLineColor(kRed);
outHistMassBayes4MCDivide->Draw("same");

file=TFile::Open("Histos_ch1_err3_sm0_MCf0_PID1_smear0_scale1.root");
outHistMassBayes4MCDivide->SetLineWidth(2);
outHistMassBayes4MCDivide->SetLineStyle(kDotted);
outHistMassBayes4MCDivide->SetLineColor(kCyan);
outHistMassBayes4MCDivide->Draw("same");
file=TFile::Open("Histos_ch1_err3_sm0_MCf0_PID1_smear0_scale-1.root");
outHistMassBayes4MCDivide->SetLineWidth(2);
outHistMassBayes4MCDivide->SetLineStyle(kDotted);
outHistMassBayes4MCDivide->SetLineColor(kBlue);
outHistMassBayes4MCDivide->Draw("same");
file=TFile::Open("Histos_ch1_err3_sm0_MCf0_PID1_smear1_scale0.root");
outHistMassBayes4MCDivide->SetLineWidth(2);
outHistMassBayes4MCDivide->SetLineStyle(kDashDotted);
outHistMassBayes4MCDivide->SetLineColor(kYellow);
outHistMassBayes4MCDivide->Draw("same");
file=TFile::Open("Histos_ch1_err3_sm0_MCf0_PID1_smear1_scale1.root");
outHistMassBayes4MCDivide->SetLineWidth(2);
outHistMassBayes4MCDivide->SetLineStyle(kDashDotted);
outHistMassBayes4MCDivide->SetLineColor(kGreen);
outHistMassBayes4MCDivide->Draw("same");
file=TFile::Open("Histos_ch1_err3_sm0_MCf0_PID1_smear1_scale-1.root");
outHistMassBayes4MCDivide->SetLineWidth(2);
outHistMassBayes4MCDivide->SetLineStyle(kDotted);
outHistMassBayes4MCDivide->SetLineColor(kMagenta);
outHistMassBayes4MCDivide->Draw("same");

TLatex latex;
latex.SetTextFont(62);
latex.SetTextSize(0.045);    
latex.DrawLatex(87,3600,"CMS simulation internal");

TLegend *leg = new TLegend(0.25,0.15,0.8,0.5,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(0);
leg->SetLineStyle(1);
leg->SetLineWidth(1);
leg->SetFillColor(19);
leg->SetFillStyle(0);
TLegendEntry *entry=leg->AddEntry("outHistMassBayes4MC","outHistMassBayes4MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDashed);
entry->SetLineColor(kRed);
entry=leg->AddEntry("a","outHistMassBayes4MC, smear 1%","L");
entry->SetLineWidth(2);
entry->SetLineStyle(kDotted);
entry->SetLineColor(kYellow);
entry=leg->AddEntry("b","outHistMassBayes4MC, scale +1%","L");
entry->SetLineWidth(2);
entry->SetLineStyle(kDotted);
entry->SetLineColor(kCyan);
entry=leg->AddEntry("c","outHistMassBayes4MC, scale -1%","L");
entry->SetLineWidth(2);
entry->SetLineStyle(kDotted);
entry->SetLineColor(kBlue);
entry=leg->AddEntry("d","outHistMassBayes4MC, scale +1%, smear 1%","L");
entry->SetLineWidth(2);
entry->SetLineStyle(kDashDotted);
entry->SetLineColor(kGreen);
entry=leg->AddEntry("e","outHistMassBayes4MC, scale -1%, smear 1%","L");
entry->SetLineWidth(2);
entry->SetLineStyle(kDashDotted);
entry->SetLineColor(kMagenta);
leg->Draw();

trueH->Print("trueH_ES_CF.pdf");
}
