{
	
gROOT->ForceStyle(); 
gStyle->SetPadLeftMargin(0.18);
gStyle->SetPadRightMargin(0.18);
gStyle->SetPadBottomMargin(0.13);
gStyle->SetOptStat(0);


TCanvas *trueH= new TCanvas ("trueH", "trueH", 700, 700);
trueH->Divide(2,2);

TFile *file=0;
file=TFile::Open("Histos_ch0_err3_sm0_MCf0_PID1_smear0_scale0.root");

trueH->cd(1);
gPad->SetLogx();
gPad->SetLogy();
gPad->SetTicks();
trueHistMC->SetTitle("Electron channel");
trueHistMC->SetLineWidth(2);
trueHistMC->SetLineStyle(kSolid);
trueHistMC->SetLineColor(kBlack);
trueHistMC->GetXaxis()->SetTitle("True photon p_{T} [GeV]"); 
trueHistMC->GetYaxis()->SetTitle("Entries"); 
trueHistMC->GetXaxis()->SetMoreLogLabels(); 
trueHistMC->GetYaxis()->SetMoreLogLabels(); 
trueHistMC->GetXaxis()->SetTitleOffset(1.3); 
trueHistMC->GetYaxis()->SetTitleOffset(1.7); 
trueHistMC->GetXaxis()->SetLabelFont(62); 
trueHistMC->GetYaxis()->SetLabelFont(62); 
trueHistMC->GetXaxis()->SetTitleFont(62); 
trueHistMC->GetYaxis()->SetTitleFont(62); 
trueHistMC->GetXaxis()->SetLabelSize(0.045); 
trueHistMC->GetYaxis()->SetLabelSize(0.045); 
trueHistMC->GetXaxis()->SetTitleSize(0.048); 
trueHistMC->GetYaxis()->SetTitleSize(0.048); 
trueHistMC->GetXaxis()->SetNoExponent(); 
trueHistMC->GetYaxis()->SetNoExponent(); 
trueHistMC->Draw();
outHistBayes4MC->SetLineWidth(2);
outHistBayes4MC->SetLineStyle(kDashed);
outHistBayes4MC->SetLineColor(kRed);
outHistBayes4MC->Draw("same");
outHistBayes3MC->SetLineWidth(2);
outHistBayes3MC->SetLineStyle(kDashed);
outHistBayes3MC->SetLineColor(kBlue);
outHistBayes3MC->Draw("same");
outHistBayes5MC->SetLineWidth(2);
outHistBayes5MC->SetLineStyle(kDashed);
outHistBayes5MC->SetLineColor(kGreen);
outHistBayes5MC->Draw("same");
outHistSvd5MC->SetLineWidth(2);
outHistSvd5MC->SetLineStyle(kDotted);
outHistSvd5MC->SetLineColor(kMagenta);
outHistSvd5MC->Draw("same");
outHistSvd8MC->SetLineWidth(2);
outHistSvd8MC->SetLineStyle(kDotted);
outHistSvd8MC->SetLineColor(kCyan);
outHistSvd8MC->Draw("same");
outHistBinByBinMC->SetLineWidth(2);
outHistBinByBinMC->SetLineStyle(kDashDotted);
outHistBinByBinMC->SetLineColor(kYellow);
outHistBinByBinMC->Draw("same");

TLatex latex;
latex.SetTextFont(62);
latex.SetTextSize(0.045);    
latex.DrawLatex(23,1900,"CMS simulation internal");

TLegend *leg = new TLegend(0.2,0.15,0.6,0.5,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(0);
leg->SetLineStyle(1);
leg->SetLineWidth(1);
leg->SetFillColor(19);
leg->SetFillStyle(0);
TLegendEntry *entry=leg->AddEntry("trueHistMC","trueHistMC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kSolid);
entry->SetLineColor(kBlack);
entry=leg->AddEntry("outHistBayes4MC","outHistBayes4MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDashed);
entry->SetLineColor(kRed);
entry=leg->AddEntry("outHistBayes3MC","outHistBayes3MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDashed);
entry->SetLineColor(kBlue);
entry=leg->AddEntry("outHistBayes5MC","outHistBayes5MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDashed);
entry->SetLineColor(kGreen);
entry=leg->AddEntry("outHistSvd5MC","outHistSvd5MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDotted);
entry->SetLineColor(kMagenta);
entry=leg->AddEntry("outHistSvd8MC","outHistSvd8MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDotted);
entry->SetLineColor(kCyan);
entry=leg->AddEntry("outHistBinByBinMC","outHistBinByBinMC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDashDotted);
entry->SetLineColor(kYellow);
leg->Draw();

trueH->cd(3);
gPad->SetLogx();
gPad->SetLogy();
gPad->SetTicks();
trueHistMassMC->SetTitle("Electron channel");
trueHistMassMC->SetLineWidth(2);
trueHistMassMC->SetLineStyle(kSolid);
trueHistMassMC->SetLineColor(kBlack);
trueHistMassMC->GetXaxis()->SetTitle("True ll#gamma mass [GeV]"); 
trueHistMassMC->GetYaxis()->SetTitle("Entries"); 
trueHistMassMC->GetXaxis()->SetMoreLogLabels(); 
trueHistMassMC->GetYaxis()->SetMoreLogLabels(); 
trueHistMassMC->GetXaxis()->SetTitleOffset(1.3); 
trueHistMassMC->GetYaxis()->SetTitleOffset(1.7); 
trueHistMassMC->GetXaxis()->SetLabelFont(62); 
trueHistMassMC->GetYaxis()->SetLabelFont(62); 
trueHistMassMC->GetXaxis()->SetTitleFont(62); 
trueHistMassMC->GetYaxis()->SetTitleFont(62); 
trueHistMassMC->GetXaxis()->SetLabelSize(0.045); 
trueHistMassMC->GetYaxis()->SetLabelSize(0.045); 
trueHistMassMC->GetXaxis()->SetTitleSize(0.048); 
trueHistMassMC->GetYaxis()->SetTitleSize(0.048); 
trueHistMassMC->GetXaxis()->SetNoExponent(); 
trueHistMassMC->GetYaxis()->SetNoExponent(); 
trueHistMassMC->Draw();
outHistMassBayes4MC->SetLineWidth(2);
outHistMassBayes4MC->SetLineStyle(kDashed);
outHistMassBayes4MC->SetLineColor(kRed);
outHistMassBayes4MC->Draw("same");
outHistMassBayes3MC->SetLineWidth(2);
outHistMassBayes3MC->SetLineStyle(kDashed);
outHistMassBayes3MC->SetLineColor(kBlue);
outHistMassBayes3MC->Draw("same");
outHistMassBayes5MC->SetLineWidth(2);
outHistMassBayes5MC->SetLineStyle(kDashed);
outHistMassBayes5MC->SetLineColor(kGreen);
outHistMassBayes5MC->Draw("same");
outHistMassSvd5MC->SetLineWidth(2);
outHistMassSvd5MC->SetLineStyle(kDotted);
outHistMassSvd5MC->SetLineColor(kMagenta);
outHistMassSvd5MC->Draw("same");
outHistMassSvd8MC->SetLineWidth(2);
outHistMassSvd8MC->SetLineStyle(kDotted);
outHistMassSvd8MC->SetLineColor(kCyan);
outHistMassSvd8MC->Draw("same");
outHistMassBinByBinMC->SetLineWidth(2);
outHistMassBinByBinMC->SetLineStyle(kDashDotted);
outHistMassBinByBinMC->SetLineColor(kYellow);
outHistMassBinByBinMC->Draw("same");

TLatex latex;
latex.SetTextFont(62);
latex.SetTextSize(0.045);    
latex.DrawLatex(87,1900,"CMS simulation internal");

TLegend *leg = new TLegend(0.25,0.15,0.78,0.5,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(0);
leg->SetLineStyle(1);
leg->SetLineWidth(1);
leg->SetFillColor(19);
leg->SetFillStyle(0);
TLegendEntry *entry=leg->AddEntry("trueHistMassMC","trueHistMassMC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kSolid);
entry->SetLineColor(kBlack);
entry=leg->AddEntry("outHistMassBayes4MC","outHistMassBayes4MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDashed);
entry->SetLineColor(kRed);
entry=leg->AddEntry("outHistMassBayes3MC","outHistMassBayes3MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDashed);
entry->SetLineColor(kBlue);
entry=leg->AddEntry("outHistMassBayes5MC","outHistMassBayes5MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDashed);
entry->SetLineColor(kGreen);
entry=leg->AddEntry("outHistMassSvd5MC","outHistMassSvd5MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDotted);
entry->SetLineColor(kMagenta);
entry=leg->AddEntry("outHistMassSvd8MC","outHistMassSvd8MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDotted);
entry->SetLineColor(kCyan);
entry=leg->AddEntry("outHistMassBinByBinMC","outHistMassBinByBinMC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDashDotted);
entry->SetLineColor(kYellow);
leg->Draw();


file=TFile::Open("Histos_ch1_err3_sm0_MCf0_PID1_smear0_scale0.root");

trueH->cd(2);
gPad->SetLogx();
gPad->SetLogy();
gPad->SetTicks();
trueHistMC->SetTitle("Muon channel");
trueHistMC->SetLineWidth(2);
trueHistMC->SetLineStyle(kSolid);
trueHistMC->SetLineColor(kBlack);
trueHistMC->GetXaxis()->SetTitle("True photon p_{T} [GeV]"); 
trueHistMC->GetYaxis()->SetTitle("Entries"); 
trueHistMC->GetXaxis()->SetMoreLogLabels(); 
trueHistMC->GetYaxis()->SetMoreLogLabels(); 
trueHistMC->GetXaxis()->SetTitleOffset(1.3); 
trueHistMC->GetYaxis()->SetTitleOffset(1.7); 
trueHistMC->GetXaxis()->SetLabelFont(62); 
trueHistMC->GetYaxis()->SetLabelFont(62); 
trueHistMC->GetXaxis()->SetTitleFont(62); 
trueHistMC->GetYaxis()->SetTitleFont(62); 
trueHistMC->GetXaxis()->SetLabelSize(0.045); 
trueHistMC->GetYaxis()->SetLabelSize(0.045); 
trueHistMC->GetXaxis()->SetTitleSize(0.048); 
trueHistMC->GetYaxis()->SetTitleSize(0.048); 
trueHistMC->GetXaxis()->SetNoExponent(); 
trueHistMC->GetYaxis()->SetNoExponent(); 
trueHistMC->Draw();
outHistBayes4MC->SetLineWidth(2);
outHistBayes4MC->SetLineStyle(kDashed);
outHistBayes4MC->SetLineColor(kRed);
outHistBayes4MC->Draw("same");
outHistBayes3MC->SetLineWidth(2);
outHistBayes3MC->SetLineStyle(kDashed);
outHistBayes3MC->SetLineColor(kBlue);
outHistBayes3MC->Draw("same");
outHistBayes5MC->SetLineWidth(2);
outHistBayes5MC->SetLineStyle(kDashed);
outHistBayes5MC->SetLineColor(kGreen);
outHistBayes5MC->Draw("same");
outHistSvd5MC->SetLineWidth(2);
outHistSvd5MC->SetLineStyle(kDotted);
outHistSvd5MC->SetLineColor(kMagenta);
outHistSvd5MC->Draw("same");
outHistSvd8MC->SetLineWidth(2);
outHistSvd8MC->SetLineStyle(kDotted);
outHistSvd8MC->SetLineColor(kCyan);
outHistSvd8MC->Draw("same");
outHistBinByBinMC->SetLineWidth(2);
outHistBinByBinMC->SetLineStyle(kDashDotted);
outHistBinByBinMC->SetLineColor(kYellow);
outHistBinByBinMC->Draw("same");

TLatex latex;
latex.SetTextFont(62);
latex.SetTextSize(0.045);    
latex.DrawLatex(23,2800,"CMS simulation internal");

TLegend *leg = new TLegend(0.2,0.15,0.6,0.5,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(0);
leg->SetLineStyle(1);
leg->SetLineWidth(1);
leg->SetFillColor(19);
leg->SetFillStyle(0);
TLegendEntry *entry=leg->AddEntry("trueHistMC","trueHistMC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kSolid);
entry->SetLineColor(kBlack);
entry=leg->AddEntry("outHistBayes4MC","outHistBayes4MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDashed);
entry->SetLineColor(kRed);
entry=leg->AddEntry("outHistBayes3MC","outHistBayes3MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDashed);
entry->SetLineColor(kBlue);
entry=leg->AddEntry("outHistBayes5MC","outHistBayes5MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDashed);
entry->SetLineColor(kGreen);
entry=leg->AddEntry("outHistSvd5MC","outHistSvd5MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDotted);
entry->SetLineColor(kMagenta);
entry=leg->AddEntry("outHistSvd8MC","outHistSvd8MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDotted);
entry->SetLineColor(kCyan);
entry=leg->AddEntry("outHistBinByBinMC","outHistBinByBinMC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDashDotted);
entry->SetLineColor(kYellow);
leg->Draw();

trueH->cd(4);
gPad->SetLogx();
gPad->SetLogy();
gPad->SetTicks();
trueHistMassMC->SetTitle("Muon channel");
trueHistMassMC->SetLineWidth(2);
trueHistMassMC->SetLineStyle(kSolid);
trueHistMassMC->SetLineColor(kBlack);
trueHistMassMC->GetXaxis()->SetTitle("True ll#gamma mass [GeV]"); 
trueHistMassMC->GetYaxis()->SetTitle("Entries"); 
trueHistMassMC->GetXaxis()->SetMoreLogLabels(); 
trueHistMassMC->GetYaxis()->SetMoreLogLabels(); 
trueHistMassMC->GetXaxis()->SetTitleOffset(1.3); 
trueHistMassMC->GetYaxis()->SetTitleOffset(1.7); 
trueHistMassMC->GetXaxis()->SetLabelFont(62); 
trueHistMassMC->GetYaxis()->SetLabelFont(62); 
trueHistMassMC->GetXaxis()->SetTitleFont(62); 
trueHistMassMC->GetYaxis()->SetTitleFont(62); 
trueHistMassMC->GetXaxis()->SetLabelSize(0.045); 
trueHistMassMC->GetYaxis()->SetLabelSize(0.045); 
trueHistMassMC->GetXaxis()->SetTitleSize(0.048); 
trueHistMassMC->GetYaxis()->SetTitleSize(0.048); 
trueHistMassMC->GetXaxis()->SetNoExponent(); 
trueHistMassMC->GetYaxis()->SetNoExponent(); 
trueHistMassMC->Draw();
outHistMassBayes4MC->SetLineWidth(2);
outHistMassBayes4MC->SetLineStyle(kDashed);
outHistMassBayes4MC->SetLineColor(kRed);
outHistMassBayes4MC->Draw("same");
outHistMassBayes3MC->SetLineWidth(2);
outHistMassBayes3MC->SetLineStyle(kDashed);
outHistMassBayes3MC->SetLineColor(kBlue);
outHistMassBayes3MC->Draw("same");
outHistMassBayes5MC->SetLineWidth(2);
outHistMassBayes5MC->SetLineStyle(kDashed);
outHistMassBayes5MC->SetLineColor(kGreen);
outHistMassBayes5MC->Draw("same");
outHistMassSvd5MC->SetLineWidth(2);
outHistMassSvd5MC->SetLineStyle(kDotted);
outHistMassSvd5MC->SetLineColor(kMagenta);
outHistMassSvd5MC->Draw("same");
outHistMassSvd8MC->SetLineWidth(2);
outHistMassSvd8MC->SetLineStyle(kDotted);
outHistMassSvd8MC->SetLineColor(kCyan);
outHistMassSvd8MC->Draw("same");
outHistMassBinByBinMC->SetLineWidth(2);
outHistMassBinByBinMC->SetLineStyle(kDashDotted);
outHistMassBinByBinMC->SetLineColor(kYellow);
outHistMassBinByBinMC->Draw("same");

TLatex latex;
latex.SetTextFont(62);
latex.SetTextSize(0.045);    
latex.DrawLatex(87,3600,"CMS simulation internal");

TLegend *leg = new TLegend(0.25,0.15,0.78,0.5,NULL,"brNDC");
leg->SetTextFont(62);
leg->SetLineColor(0);
leg->SetLineStyle(1);
leg->SetLineWidth(1);
leg->SetFillColor(19);
leg->SetFillStyle(0);
TLegendEntry *entry=leg->AddEntry("trueHistMassMC","trueHistMassMC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kSolid);
entry->SetLineColor(kBlack);
entry=leg->AddEntry("outHistMassBayes4MC","outHistMassBayes4MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDashed);
entry->SetLineColor(kRed);
entry=leg->AddEntry("outHistMassBayes3MC","outHistMassBayes3MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDashed);
entry->SetLineColor(kBlue);
entry=leg->AddEntry("outHistMassBayes5MC","outHistMassBayes5MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDashed);
entry->SetLineColor(kGreen);
entry=leg->AddEntry("outHistMassSvd5MC","outHistMassSvd5MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDotted);
entry->SetLineColor(kMagenta);
entry=leg->AddEntry("outHistMassSvd8MC","outHistMassSvd8MC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDotted);
entry->SetLineColor(kCyan);
entry=leg->AddEntry("outHistMassBinByBinMC","outHistMassBinByBinMC","L");
entry->SetLineWidth(3);
entry->SetLineStyle(kDashDotted);
entry->SetLineColor(kYellow);
leg->Draw();

trueH->Print("trueH_method.pdf");
}
